name: CryptOfNecromancer
version: ${project.version}
main: net.kunmc.lab.cryptofnecromancer.CryptOfNecromancer
api-version: 1.15
authors: [Peyang, YukiAt]
description: Rythm Dance!
website: https://kunmc.net/
commands:
  crypt:
    permission: CryptOfNecromancer.command
permissions:
  CryptOfNecromancer.command:
    default: op
